config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :link_lists,
            :param => :qualified_id,
            :constraints => { :qualified_id => %r|[^/\-]+-[^/.]+| },
            :path => :lists do
    collection do
      post 'import'
    end
  end

  resources :drs_list_objects,
              :param => :qualified_id,
              :constraints => { :qualified_id => %r|[^/\-]+-[^/.]+| },
              :path => :lists do
      collection do
        post 'import'
      end
    end
    
  get 'meta/:ext_id_type/:ext_id' => 'link_lists#meta', :defaults => {:format => :json}
  get 'types'                     => 'link_lists#types'
  get 'types/:ext_id_type'        => 'link_lists#index', :constraints => {:ext_id_type => /[[:alnum:]]+/}

  root :to => 'link_lists#index'
end

app/models/link_list.rb
# coding: utf-8
require 'csv'

# Monkeypatch for Roo::Excelx because we don't want any floats
class Roo::Excelx
  def hl_cell(row, col, sheet = nil)
    if self.celltype(row, col, sheet) == :float
      self.excelx_value(row, col, sheet)
    else
      self.cell(row, col, sheet)
    end
  end
end

class LinkList < ActiveRecord::Base
  has_many :links, -> { order('position ASC')}, :dependent => :destroy
  accepts_nested_attributes_for :links, :reject_if => :all_blank, :allow_destroy => true

  attr_accessor :repository, :institution, :accdate,
        :related_links
   
  #Default values for repository, insitution, and accdate.     
  after_initialize do |ll|
    @repository = 'Harvard University Library'
    @institution = 'Harvard University'
    @accdate = Time.now.to_date.to_formatted_s(:rfc822)
  end
          
  validates :ext_id, :presence => true
  validates :ext_id_type, :presence => true, :inclusion => MetadataSources.keys

  mount_uploader :image, ImageUploader

  after_create do |ll|
    Ledger.create(:event_type => 'create',
                  :user_email => ll.last_touched_by,
                  :ext_id => ll.ext_id,
                  :ext_id_type => ll.ext_id_type,
                  :serialized_linklist => ll.links.to_json,
                  :time => ll.created_at)
  end

  after_update do |ll|
    Ledger.create(:event_type => 'update',
                  :user_email => ll.last_touched_by,
                  :ext_id => ll.ext_id,
                  :ext_id_type => ll.ext_id_type,
                  :serialized_linklist => ll.links.to_json,
                  :time => ll.updated_at)
  end

  after_destroy do |ll|
    Ledger.create(:event_type => 'destroy',
                  :user_email => ll.last_touched_by,
                  :ext_id => ll.ext_id,
                  :ext_id_type => ll.ext_id_type,
                  :serialized_linklist => ll.links.to_json,
                  :time => DateTime.now)
  end

  # Override to force use of ext_id as identifier
  def to_param
    "#{ext_id_type}-#{ext_id}"
  end

  # Get URL for bibliographic record based on template
  def url
    b = binding
    b.local_variable_set(:ext_id, ext_id)
    b.local_variable_set(:ext_id_type, ext_id_type)
    eval(Erubi::Engine.new(MetadataSources[ext_id_type]['templates']['record_url']).src, b)
  end

  # Ephemeral instance var used in audit functionality
  def last_touched_by
    @last_touched_by || '<Admin Console>'
  end

  def last_touched_by=(email)
    @last_touched_by = email
  end

  # Helper for import functions below
  def process_header_field(field)
    (key, content, extra) = *field
    case key
    when /^ext_id_type/i
      raise "Invalid EXT_ID_TYPE" unless MetadataSources.key?(content)
      self.ext_id_type = content
    when /^ext_id/i
      raise "EXT_ID header MUST be preceded by valid EXT_ID_TYPE" unless self.ext_id_type
      self.ext_id = MetadataSources[self.ext_id_type]['id_proc'].call(content)
    when /^continues/i
      self.continues_name = content
      self.continues_url = extra
    when /^continued by/i
      self.continued_by_name = content
      self.continued_by_url = extra
    when /^fts_search/i
      # Regex here is specific to Harvard's FTS search params - portability issues ahoy!
      self.fts_search_url = content.sub(/Q=.*?(&|$)/, '')
    when /^fts_nodate/i
      self.dateable = false
    when key.blank?
    # Nothing
    else
      self.comment = "#{self.comment}\n#{key} #{content}".lstrip
    end
  end

  # Converts from .xlsx format, treating all fields as strings.
  # FIXME: Currently assumes :ext_id_type => 'hollis' (relies on default in DB)
  #        Above applies to CSV import as well
  #
  # Note that indexing starts from 1, because spreadsheets ¯\_(ツ)_/¯
  def self.import_xlsx(excel)
    result = LinkList.new

    # Find split between headers and content ()
    separator = (excel.find_index {|row| row[0] == 'CONTENT_LIST'} + 1) || # array_index + 1 == spreadsheet_index
                raise(StandardError, "No CONTENT_LIST in excel")

    (1...separator).each do |row_i|
      result.process_header_field((1..3).map {|col_i| excel.hl_cell row_i, col_i })
    end

    # process content
    result.links = ((separator+1)..excel.last_row).map do |row_i|
      (label,url) = *((1..2).map {|col_i| excel.hl_cell row_i, col_i })
      Link.new(:name => label, :url => url)
    end

    result
  end

  # Largely identical to above, but CSV is less weird
  # index is zero, everything is a string no matter what
  # Could (should?) probably be refactored into one method
  def self.import_csv(csv)
    result = LinkList.new

    # Find split between headers and content ()
    separator = (csv.find_index {|row| row[0] == 'CONTENT_LIST'}) ||
                raise(StandardError, "No CONTENT_LIST in csv")

    (0...separator).each do |row_i|
      result.process_header_field((0..2).map {|col_i| csv[row_i][col_i]})
    end

    # process content
    result.links = ((separator+1)...csv.count).map do |row_i|
      (label,url) = *((0..1).map {|col_i| csv[row_i][col_i]})
      Link.new(:name => label, :url => url)
    end

    result
  end

  def fetch_metadata
 	  md = Metadata.new(attributes.slice('ext_id', 'ext_id_type'))
	  md.fetch_metadata
    self.cached_metadata = md.body
    self.title = md.title
    self.publication = md.publication
    self.author = md.author
    self
  end


  def export_csv
    CSV.generate(:encoding => 'utf-8') do |csv|
      csv << ['EXT_ID_TYPE', ext_id_type]
      csv << ['EXT_ID', ext_id]
      csv << ['FTS_Search', fts_search_url] unless fts_search_url.blank?
      csv << ['FTS_NoDate'] unless dateable?
      csv << ['Continues:', continues_name, continues_url] unless continues_name.blank?
      csv << ['Continued by:', continued_by_name, continued_by_url] unless continued_by_name.blank?
      unless comment.blank?
        comment.lines.each do |line|
          if line.index(':')
            csv << [line[0..line.index(':')], line.sub(/[^:]+?:\s+/, '').chomp]
          else
            csv << [line]
          end
        end
      end
      csv << ['CONTENT_LIST']
      links.each do |link|
        csv << link.attributes.slice(*%w|name url|).values
      end
    end
  end

end

app/controllers/link_lists_controller.rb
class LinkListsController < ApplicationController
  before_action :authenticate_login!, :except => [:index, :show, :meta]
  after_action :allow_iframe, only: :show

  #### Collection actions

  def index
    params.permit(:ext_id_type)
      @link_lists = LinkList.all
      if params[:ext_id_type]
        @typed = params[:ext_id_type]
        @link_lists = @link_lists.where(:ext_id_type => params[:ext_id_type])
      end       
  end

  def new
    flash.now[:warning] = "This is a new record, and has not been saved to the database."
    @link_list = LinkList.new
  end

  def create
    @link_list = LinkList.new(link_list_params)
    @link_list.last_touched_by = current_user.email
    if @link_list.save
      flash[:notice] = "#{@link_list.ext_id} created successfully!"
      respond_to do |format|
        format.html { redirect_to @link_list }
      end
    end
  end

  def types
    @types = LinkList.distinct(:ext_id_type).pluck(:ext_id_type)
  end

  def import
    # Handle params
    params.require(:import_link_lists).permit(:xlsx)
    file = params[:import_link_lists][:xlsx]

    if file.original_filename.match /\.xlsx$/
      tfile = Tempfile.new(['excel', '.xlsx'])
    else
      tfile = Tempfile.new(['csv', '.csv'])
    end
    tfile.binmode
    tfile.write file.read
    tfile.close

    if file.original_filename.match /\.xlsx$/
      @link_list = LinkList.import_xlsx(Roo::Excelx.new(tfile.path))
    else
      @link_list = LinkList.import_csv(CSV.read(tfile.path))
    end

    tfile.unlink

    flash.now[:warning] = "Your record has been imported, but will not be saved to the database until you submit it."
    respond_to do |format|
      format.html { render :action => :new }
    end
  end

  # AJAX route
  def meta
    params.permit(:ext_id, :ext_id_type)
    md = Metadata.new(params.slice(:ext_id, :ext_id_type))
    md.fetch_metadata

    ll = LinkList.find_by(md.to_h.slice(:ext_id, :ext_id_type))

    if ll
      if md.body.blank?
        if ll && ll.cached_metadata
          md.body = ll.cached_metadata
          md.populate
        end
      else
        ll.cached_metadata = md.body
        ll.save!
      end
    end
    respond_to do |f|
      f.json { render :json => md.as_json }
    end
  end


  ### Member actions

  def show
    splitid = split_qualified_id(params[:qualified_id])
    @lvtype = splitid[:ext_id_type]
    if splitid[:ext_id_type] == 'drs'
      @link_list = DRSLinkList.display_object(splitid[:ext_id])
      @page_title = !@link_list.mets_title.is_a?(Array) && !@link_list.mets_title.blank? ? @link_list.mets_title : ''
      if @link_list.mets_title.is_a?(Array)
        delimiter = ""
        if @link_list.mets_title.length == 1
          @page_title = @link_list.mets_title.first
        else
          @link_list.mets_title.each do |t|
            @page_title = @page_title + delimiter + t
            delimiter = ", "
            end
        end
      end
      
    else
      @link_list = LinkList.includes(:links).find_by!(split_qualified_id(params[:qualified_id]))
      @page_title = @link_list.title
    end
      
    @title = @link_list.title
    @authors = !@link_list.author.blank? ? @link_list.author.split("\n") : []
    @publication = !@link_list.publication.blank? ? @link_list.publication.split("\n") : []

    
    respond_to do |f|
      f.html
      f.csv {
        headers['Content-Disposition'] = "attachment; filename=\"#{@link_list.ext_id_type}-#{@link_list.ext_id}.csv\""
        headers['Content-Type'] ||= 'text/csv'
      }
    end

  end

  def edit
    @link_list = LinkList.includes(:links).find_by!(split_qualified_id(params[:qualified_id]))
  end

  def update
    @link_list = LinkList.find_by!(split_qualified_id(params[:qualified_id]))
    @link_list.last_touched_by = current_user.email
    @link_list.attributes = link_list_params

    if @link_list.save
      flash[:notice] = "#{@link_list.ext_id} updated successfully!"
      redirect_to :action => :show
    else
      flash[:error] = "Failed to update #{@link_list.ext_id}!"
      redirect_to :back
    end
  end

  def destroy
    @link_list = LinkList.find_by!(split_qualified_id(params[:qualified_id]))
    @link_list.last_touched_by = current_user.email
    if @link_list.destroy
      flash[:notice] = "#{@link_list.ext_id} sucessfully deleted."
      respond_to do |format|
        format.html { redirect_to link_lists_path }
      end
    end
  end
  
  def test
    testmodel = Test.new()
    @mystring = testmodel.get_string()
  end

  private
    def link_list_params
      params.require(:link_list).permit(:ext_id,
                                        :ext_id_type,
                                        :qualified_id,
                                        :title,
                                        :author,
                                        :publication,
                                        :image,
                                        :remove_image,
                                        :continues_name,
                                        :continues_url,
                                        :continued_by_name,
                                        :continued_by_url,
                                        :fts_search_url,
                                        :dateable,
                                        :comment,
                                        :links_attributes => [:id, :name, :url, :_destroy])
    end

    ### Helper Methods ###
    def split_qualified_id(q_id)
      #HashWithIndifferentAccess.new([:ext_id_type, :ext_id].zip(q_id.split('-',2)).to_h)
      HashWithIndifferentAccess.new(Hash[[:ext_id_type, :ext_id].zip(q_id.split('-',2))])
    end
    
    def allow_iframe
      response.headers.except! 'X-Frame-Options'
    end

end

app/views/link_lists/_link_fields.html.erb
<%= f.inputs :class => 'inputs nested-fields links-nf' do %>
  <%= f.input :name %>
  <%= f.input :url, :label => 'URL' %>
  <div class="links">
    <%= link_to_remove_association "Remove", f, :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/link_lists/_modal.html.erb
<%# Takes locals (title, fields) %>
<div id="modal-<%= title.downcase %>" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <div class="modal-body">
        <ul class="modal-fields">
          <% fields.each do |field| %>
            <li class="modal-field modal-field-<%= field.downcase %>">
              <p class="label"><%= field %>:</p>
              <pre class="content"></pre>
            </li>
          <% end %>
        </ul>
        <div class="modal-blank" style="display: none;">
          Metadata for this record is unavailable at this time.
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary meta-accept" data-dismiss="modal">Replace Fields</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/link_lists/_modal_dialogs.html.erb
<div id="modal-cite" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Citation</h4>
      </div>
      <div class="modal-body">
      	<p>Please note that a complete citation may require additional information
      	(document date, author name, range of pages/sequence numbers, etc.)</p>
	      <ul>
	        <li><span class="citelabel plink">Persistent Link</span> <a href="<%= @link_list.url %>"><%= @link_list.url %></a></li>
	        <li> 
	        	<% unless @link_list.title.blank? %>
	        		<% if !@link_list.title.is_a?(Array) %>
	        			<span class="citelabel desc">Description</span> <%= @link_list.title %>
	        		<% else %>
				      <% case @link_list.title.length %>
				      <% when 1 %>
				      	<span class="citelabel desc">Description</span> <%= @link_list.title.first %>
				      <% else %>
				          <span class="citelabel desc">Description</span> <% @link_list.title.each do |t| %>
				            <%= t %><br/>
				          <% end %>
				      <% end %>
				  <% end %>
			  <% end %>        
	        </li> 
	        <li><span class="citelabel repo">Repository</span> <%= @link_list.repository %></li>
	        <li><span class="citelabel inst">Institution</span> <%= @link_list.institution %></li>
	        <li><span class="citelabel access">Accessed</span> <%= @link_list.accdate %></li>
	      </ul>	  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="modal-links" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Related Links</h4>
      </div>
      <div class="modal-body">
      	<p><strong>Links relating to: </strong> <%= @link_list.title %></p>
		<p><strong>Related Links</strong> take you to information outside of List View that relates to 
		the displayed document. E.g.,  a link to a description of the document in HOLLIS,  to a finding aid
		in OASIS, or to a specialized web site with additional information.</p>
		<p>Click on the link and the information will display in a new browser window. </p>
		<% if @link_list.ext_id_type == 'hollis' %>
	    	<li>Aleph <%= link_to @link_list.url, :target => '_blank' %></li>
	    <% end %>
		<% if !@link_list.related_links.blank? %>
	      <% @link_list.related_links.each do |link| %>
	      <li>
	      	<% if (!link.related_url().nil?) then %>
	      		<% if (link.related_url().start_with?("http://") || link.related_url().start_with?("www.") || link.related_url().start_with?("https://")) %>
	        		<%= link.type %> <%= link_to link.label, link.related_url(), :target => '_blank' %>
	        	<% else %>
	        		<%= link.type %> <%= link.label %>: <%= link.related_url() %>
	        	<% end %>
	        <% else  %>
	        <%= link.type %> <%= link.label %>
	        <% end %>
	      </li>
	    <% end %> 
	   <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div id="modal-share" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Share</h4>
      </div>
      <div class="modal-body">
      		 <div class="social-likes">
				<div class="facebook" title="Share link on Facebook">Facebook</div>
				<div class="twitter" title="Share link on Twitter">Twitter</div>
				<div class="plusone" title="Share link on Google+">Google+</div>
				<div class="pinterest" title="Share image on Pinterest" data-media="">Pinterest</div>
			</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/link_lists/_modal_search.html.erb
<div id="modal-search" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Full Text Search</h4>
      </div>
      <div class="modal-body">
        <div class="search-box">
		    <form class="formtastic" id="fts" target="_blank" action="<%= @link_list.fts_search_url.sub(/S=[^&]+/, '') %>" method='GET'>
		      <p>Full Text Search</p>
		      <div class="input-group search-field">
		        <input name="S" type="hidden" value="<%== @link_list.fts_search_url.match(/(?<=S=)[^&]+/i).to_s %>" />
		        <input name="Q" class="form-control" type="text" placeholder="Enter search terms here" />
		      </div>
		      <div  class="search-options">
		      <% if @link_list.dateable? %>
		          <div class="input-group date-range">
		            <span class="nobreak"><label for="L">From:</label>&nbsp;<input name="L" placeholder="YYYY(/MM(/DD))" /></span>
		            <span class="nobreak"><label for="U">To:</label>&nbsp;<input name="U" placeholder="YYYY(/MM(/DD))" /></span>
		          </div>
		          <div id="date-qualified" class="input-group date-qualified">
		            <label for="date-qualified">Include results without dates?</label>
		            <span class="nobreak">
		              <div><label for="D_Y">Yes</label>&nbsp;<%= radio_button_tag 'D', 'Y', true %></div>
		              <div><label for="D_S">No</label>&nbsp;<%= radio_button_tag 'D', 'S', false %></div>
		            </span>
		          </div>
		      <% end %>
		      <% select_options = {"relevance" => "R", "date (oldest to newest)" => "D", "title (Alphabetical)" => "A"} %>
		      <div class="sortby"><label for="O">Sort results by:</label>&nbsp;<%= select_tag "O", options_for_select(select_options, "R"), :class => 'form-control' %></span></div>
		      </div>
		    </form>
		  </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary search-accept" data-dismiss="modal">Search</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/link_lists/edit.html.erb
<%= render :partial => 'shared/forms/link_list' %>

app/views/link_lists/index.html.erb
<% content_for :subhead, "#{@typed ? @typed.capitalize : 'All'} Records" %>
<% if current_user %>
  <div class="ll-create">
    <p style="font-weight: bold">Create a new linked list from scratch.</p>
    <%= link_to "Create New Link List", new_link_list_path, :class => 'btn btn-primary' %>
  </div>
  <div class="ll-import">
    <%= semantic_form_for :import_link_lists, :url => import_link_lists_path, :method => :post, :multipart => true do |f| %>
      <%= f.inputs do %>
        <%= f.input :xlsx, :as => :file, :label => "Import Link List from an excel file" %>
      <% end %>
      <%= f.actions do %>
        <%= f.action :submit, :as => :button, :button_html => { :class => 'btn btn-primary' }, :label => 'Import' %>
      <% end %>
    <% end %>
  </div>
  <hr class="clearfix">
<% end %>
<table class="table table-striped">
  <tbody>
    <tr>
      <th>Title</th>
      <th>External ID</th>
      <th>Number of Links</th>
    </tr>
    <% @link_lists.each do |ll| %>
      <tr>
        <td>
          <% if current_user %>
            <%= link_to link_list_path(ll, :format => 'csv'),
                        :class=> 'btn btn-xs btn-info',
                        :title => 'CSV Download' do %>
              CSV <%= glyphicon 'file'%>
            <% end %>
            <%= link_to edit_link_list_path(ll),
                        :class => 'btn btn-xs btn-primary',
                        :title => 'Edit this record' do %>
              Edit <%= glyphicon 'pencil' %>
            <% end %>
          <% end %>
          <%= link_to ll.title , ll %>
        </td>

        <td><%= "#{ll.ext_id_type}-#{ll.ext_id}" %></td>
        <td><%= ll.links.size %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/link_lists/new.html.erb
<%= render :partial => 'shared/forms/link_list' %>

app/views/link_lists/show.csv.erb
<%== @link_list.export_csv %>

app/views/link_lists/show.html.erb
<% content_for :subhead, @page_title || [:ext_id_type, :ext_id].map {|m| @link_list.send(m).upcase }.join(" ") %>

<% if current_user && @link_list.ext_id_type == "hollis" %>
  <ul class="controls">
    <li>
      <%= link_to link_list_path(@link_list, :format => 'csv'), :title => 'CSV Download', :class => 'btn btn-info' do %>
        Download CSV <%= glyphicon 'file' %></span>
      <% end %>
    </li>
    <li>
      <%= link_to edit_link_list_path(@link_list), :class => 'btn btn-primary' do %>
        Edit this record <%= glyphicon'pencil' %>
      <% end %>
    </li>
    <li><%= link_to "Delete this record", link_list_path(@link_list),
              :method => :delete,
              :data => {:confirm => "Are you sure you want to delete \"#{@title}\"?"},
              :class => 'btn btn-danger' %></li>
  </ul>
<% end %>
<div class="metadata">
  <div class="image"><%= image_tag @link_list.image.url unless @link_list.image.blank? %></div>
  <% unless @title.blank? %>
    <div class="title"><span class="md-label">Title: </span><%= !@title.is_a?(Array) && !@title.blank? ? @title : '' %>
      <% if @title.is_a?(Array) %>
	      <% case @title.length %>
	      <% when 1 %>
	        <%= @title.first %>
	      <% else %>
	        <ul>
	          <% @title.each do |t| %>
	            <li><%= t %></li>
	          <% end %>
	        </ul>
	      <% end %>
	  <% end %>
    </div>
  <% end %>

  <% unless @authors.blank? %>
    <div class="author"><span class="md-label">Author: </span><%= @authors.length > 1 ? "s" : '' %>
      <% case @authors.length %>
      <% when 1 %>
        <%= @authors.first %>
      <% else %>
        <ul>
          <% @authors.each do |a| %>
            <li><%= a %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <% end %>

  <% unless @publication.blank? %>
    <div class="publication">
      <span class="md-label">Publication: </span>
      <% case @publication.length %>
      <% when 1 %>
        <%= @publication.first %>
      <% else %>
        <ul>
          <% @publication.each do |p| %>
            <li><%= p %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <% end %>
  <% if @link_list.ext_id_type == "drs" %>
	<div class="osn_id"><span class="md-label">ID: </span> <%= @link_list.osn_id %></div>
  <% end %>
</div>



<% unless @link_list.comment.blank? %>
  <div class="comment">
    <%== @link_list.comment.split(/\n/).map { |line| '<div>' << line << '</div>' }.join("\n") %>
  </div>
<% end %>


<% unless @link_list.continues_url.blank? %>
  <div class="continues">
    <b>Continues:</b> <%= link_to @link_list.continues_name, @link_list.continues_url %>
  </div>
<% end %>

<% unless @link_list.continued_by_url.blank? %>
  <div class="continued_by">
    <b>Continued By:</b> <%= link_to @link_list.continued_by_name, @link_list.continued_by_url %>
  </div>
<% end %>


<a id="#links"></a>
<table style="border: 1px solid #ddd" class="table table-striped">
  <thead>
    <tr><th>Links</th></tr>
  </thead>
  <tbody>
    <% @link_list.links.each do |link| %>
    	<tr>
    		<% if !link.url.blank? %>
        	<td><%= link_to link.name, link.url, :target => '_blank' %></td>
        	<% else %>
        	<td><%= link.name %>
        	<% end %>
      	</tr>
    <% end %>
  </tbody>
</table>

<% unless @link_list.continues_url.blank? %>
  <div class="continues">
    <b>Continues:</b> <%= link_to @link_list.continues_name, @link_list.continues_url %>
  </div>
<% end %>

<% unless @link_list.continued_by_url.blank? %>
  <div class="continued_by">
    <b>Continued By:</b> <%= link_to @link_list.continued_by_name, @link_list.continued_by_url %>
  </div>
<% end %>

<% unless @link_list.fts_search_url.blank? %>
	<%= render :partial => 'modal_search' %>
<% end %>
<%= render :partial => 'modal_dialogs' %>

app/views/link_lists/types.html.erb
<h2 style="margin-bottom: 0;">External ID Types</h2>
<p class="help-block" style="text-align:center;">Records indexed by type of external ID.</p>
<% unless @types.blank? %>
<table class="table table-striped" style="border: 1px solid #ddd, align:center;text-align:center;">
  <tbody>
    <% @types.each do |t| %>
      <tr>
        <td><%= link_to "#{t.upcase}", [types_path, t].join("/") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<h3 style="text-align:center;">There are no records.</h2>
<% end %>