config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :link_lists,
            :param => :qualified_id,
            :constraints => { :qualified_id => %r|[^/\-]+-[^/.]+| },
            :path => :lists do
    collection do
      post 'import'
    end
  end

  resources :drs_list_objects,
              :param => :qualified_id,
              :constraints => { :qualified_id => %r|[^/\-]+-[^/.]+| },
              :path => :lists do
      collection do
        post 'import'
      end
    end
    
  get 'meta/:ext_id_type/:ext_id' => 'link_lists#meta', :defaults => {:format => :json}
  get 'types'                     => 'link_lists#types'
  get 'types/:ext_id_type'        => 'link_lists#index', :constraints => {:ext_id_type => /[[:alnum:]]+/}

  root :to => 'link_lists#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_login!, :except => [:new, :create]

  # Helper methods

  def vet_password
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if params[:user][:password] != params[:user][:password_confirmation]
      flash[:error] = 'Password and confirmation must match.'
      redirect_to :back
    end
  end

  def vet_username
    if params[:user][:username].blank?
      params[:user][:username] = nil
    end
  end
  # Collection actions

  def index
    @users = User.order(:id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    vet_username
    vet_password
    if @user.save
      flash[:notice] = "User sucessfully created!"
      redirect_to @user, :action => :show
    else
      flash[:error] = "Failed to save user."
      redirect_to :back
    end
  end

  # Member actions

  def show
    @user = User.find(params[:id])
    @actions = Ledger
               .where(:user_email => @user.email)
               .order('created_at DESC')
               .limit(100)
               .pluck(:ext_id_type, :ext_id, :event_type, :created_at)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    vet_username
    vet_password

    @user.attributes = user_params
    if @user.save
      flash[:notice] = "User updated sucessfully!"
      respond_to do |f|
        f.html { redirect_to @user, :action => :show }
      end
      return
    else
      flash[:error] = "Failed to update user."
      redirect_to :back
      return false
    end
  end

  def destroy
    @user = User.find(params[:id])
    unless @user == current_user
      dead = @user.destroy!
      flash[:success] = "#{dead.username || dead.email} deleted."
    else
      flash[:error] = "You may not delete yourself.  Get someone else to delete you."
    end
    respond_to do |f|
      f.html { redirect_to users_path }
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :affiliation, :password, :password_confirmation)
  end
end

app/views/users/edit.html.erb
<%= render :partial => 'shared/forms/user' %>

app/views/users/index.html.erb
<% content_for :subhead, 'Admins' %>
<%# Buttonize, put pencil glyph on edit, x on delete? %>
<table class="table table-striped">
  <tbody>
    <tr>
      <th>User</th>
      <th>Controls</th>
    </tr>
    <% @users.each do |u| %>
      <tr><td><%= link_to (u.username || u.email), u %></td>
        <td><%= link_to edit_user_path(u),
                        :class => 'btn btn-info btn-xs',
                        :title => 'Edit User' do %>
          Edit <%= glyphicon 'pencil' %>
            <% end %>
            <%= link_to u,
                        :method => :delete,
                        :data => {:confirm => "Are you sure you want to delete #{u.username || u.email}?"},
                        :class => 'btn btn-danger btn-xs' do %>
            Delete <%= glyphicon 'trash' %>
            <% end %>
        </td></tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add User', new_user_path, :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%= render :partial => 'shared/forms/user' %>

app/views/users/show.html.erb
<% content_for :subhead, (@user.username || @user.email) %>
<div><span class="user-label">Username:</span> <%= @user.username || 'none' %></div>
<div><span class="user-label">Email:</span> <%= @user.email %></div>
<div><span class="user-label">Affiliation:</span> <%= @user.affiliation %></div>
<% if @user == current_user %>
  <%= link_to edit_user_path(@user), :class => 'btn btn-primary' do %>
    Edit <%= glyphicon 'pencil' %>
  <% end %>
<% end %>
<h3>User Activity</h3>
<p class="help-block">A list of the actions taken by this user, from most recent to most antique.</p>
<table class="table table-striped">
  <tbody>
    <tr>
      <th>Record</th>
      <th>Action taken</th>
      <th>Date/Time</th>
    </tr>
    <% @actions.each do |a| %>
      <tr>
        <td><%= a[0..1].join(':') %></td>
        <td><%= a[2] %></td>
        <%# NOTE: Only displays in server timezone %>
        <td><%= a[3].in_time_zone(Rails.configuration.time_zone).strftime("%Y-%m-%d %I:%M %P") %></td>
      </tr>
    <% end %>
  </tbody>
</table>